# Generated by Django 3.0.5 on 2020-07-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cpf',
            field=models.IntegerField(blank=True, null=True, verbose_name='CPF'),
        ),
    ]
