# Generated by Django 3.0.5 on 2020-06-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='Fotos',
            field=models.ImageField(upload_to='static/produtos/fotos/'),
        ),
    ]
