# Generated by Django 3.0.5 on 2020-06-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_auto_20200623_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='Fotos',
            field=models.ImageField(upload_to='static/produtos/fotos/'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='Fotos_2',
            field=models.ImageField(upload_to='static/produtos/fotos/'),
        ),
    ]
