# Generated by Django 3.0.5 on 2020-06-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_auto_20200630_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='Itens',
        ),
        migrations.AddField(
            model_name='produtos',
            name='Orders',
            field=models.ManyToManyField(blank=True, related_name='produto', to='loja.Pedidos'),
        ),
    ]
