# Generated by Django 3.0.5 on 2020-06-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_auto_20200630_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='Orders',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='Items',
            field=models.ManyToManyField(blank=True, related_name='pedido', to='loja.Produtos'),
        ),
    ]
