# Generated by Django 3.0.5 on 2020-07-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_auto_20200701_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cpf',
            field=models.IntegerField(verbose_name='CPF'),
        ),
    ]
