# Generated by Django 3.0.5 on 2020-07-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_auto_20200701_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cpf',
            field=models.IntegerField(blank=True, verbose_name='CPF'),
        ),
    ]
