# Generated by Django 3.0.5 on 2020-07-01 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_auto_20200701_1418'),
        ('loja', '0010_auto_20200701_1410'),
    ]

    operations = [
    ]
