# Generated by Django 3.0.5 on 2020-07-01 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0011_merge_20200701_1431'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
