# Generated by Django 3.0.5 on 2020-07-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0015_userprofile_celular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descontos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cupom', models.CharField(max_length=128)),
                ('Porcentagem_desconto', models.IntegerField()),
            ],
        ),
    ]
