# Generated by Django 3.0.5 on 2020-07-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0016_descontos'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='endereço',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
