# Generated by Django 3.0.5 on 2020-07-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0017_userprofile_endereço'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cep',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
