# Generated by Django 3.0.5 on 2020-07-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0018_userprofile_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cep',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='endereço',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
